#pragma once

#define		GAME_LEVEL_PER_TIME				20000U

#define		CARMGR_NEW_CAR_DELAY_TIME		3000U

#define		CAR_BORN_DISTANCE_FROM_HOSUNG	1200.0f

#define		BOOM_ANIMATION_DELAY	50
#define		BOOM_SHOW_TIME			300U