#pragma once

#define HOSUNG_SCREEN_X			(SCREEN_WIDTH) / 2
#define	HOSUNG_SCREEN_Y			(SCREEN_HEIGHT) / 2

#define HOSUNG_SCREEN_F_X		(SCREEN_F_WIDTH) / 2.0f
#define HOSUNG_SCREEN_F_Y		(SCREEN_F_HEIGHT) / 2.0f

#define HOSUNG_MAX_HP					100.0f
#define HOSUNG_NORMAL_SPEED				170.0f
#define HOSUNG_JUMP_SPEED				100.0f
#define	HOSUNG_JUMP_SPENDING_HP			50.0f
#define HOSUNG_FAST_SPEED				280.0f
#define HOSUNG_SPEEDING_SPENDING_HP		30.0f
#define HOSUNG_SPEEDING_TIME			2500U
#define HOSUNG_GROUND_ABOVE_HEIGHT		20.0f
#define	HOSUNG_ANGLE_SPEED				2.5f
#define	HOSUNG_LENGTH					80.0f
#define HOSUNG_HALF_LENGTH				(HOSUNG_LENGTH) / 2.0f
#define	HOSUNG_HEALTH_INCREASING_SPEED	5.0f

#define HOSUNG_NORMAL_ANIMATION_DELAY	120
#define HOSUNG_FAST_ANIMATION_DELAY		30

#define	HEALTH_BLOCK_WIDTH				16